### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by wise-introvert** [stephin007/Cowin-Vaccine-Availablity-Checker#104]
Link to the contribution guideline in broken in the readme

**Comment by stephin007** [comment]
@wise-introvert understood, can you fix that? and why are there 2 contributing.md
both in the root and inside .github? any specific reason though?

**Comment by wise-introvert** [comment]
I've opened up a pr for this fix.

Github will use the CONTRIBUTING.md in `/.github` for new contributors
