### ISSUE TITLE
Add a Hamburger icon for navitems

### ISSUE THREAD

**Issue by stephin007** [stephin007/Cowin-Vaccine-Availablity-Checker#114]
**Is your feature request related to a problem? Please describe.**
Right now, the nav items in the mobile view is just placed under the logo, which is not feasible as nav items will increase from time to time.

**Describe the solution you'd like**
A simple hamburger icon which on clicking should either show navitems as a pushdown menu or anything else, all suggestions are welcome

**Comment by Justinnn07** [comment]
@stephin007 I am assigining myself!

**Comment by stephin007** [comment]
Sure buddy 😸

**Comment by stephin007** [comment]
This feature is added in: https://github.com/stephin007/Cowin-Vaccine-Availablity-Checker/pull/124
