### ISSUE TITLE
NO instructions on how to run or how to use it

### ISSUE THREAD

**Issue by anisingh62** [stephin007/Cowin-Vaccine-Availablity-Checker#119]
Please add Instructions so that we people (noob) can use it also. As we are zero atleast give some gudiance.
I really appreciate you guys but if you would help us also will be really appreciated

**Comment by stephin007** [comment]
hey @anisingh62 apologies if you found anything difficult but if you could please check the contributing.md file
It has everything you need to know how to intialize your project in your local systems.

**Comment by stephin007** [comment]
@anisingh62 is there anything else you need to help you get started?

**Comment by anisingh62** [comment]
No sir once let me get back to my laptop after work ....and if needed will
surely ask you

**Comment by stephin007** [comment]
Adequate information was already resent, so closing this issue
