### ISSUE TITLE
Revamp About Page UI and content

### ISSUE THREAD

**Issue by stephin007** [stephin007/Cowin-Vaccine-Availablity-Checker#126]
**Is your feature request related to a problem? Please describe.**
---
Right now, the About page contains only one line which does not look good

**Describe the solution you'd like**
---
To start with we can add the following:
- Add the list of contributors for this repositories. 
- Add a better description of the App.

**Comment by stephin007** [comment]
@Justinnn07 i did not ask you to merge it! buddy
i only asked you to review and let me know any changes

**Comment by Justinnn07** [comment]
> @Justinnn07 i did not ask you to merge it! buddy
> i only asked you to review and let me know any changes
> 

Sure! 💯
