### ISSUE TITLE
Better UI for Pagination

### ISSUE THREAD

**Issue by Justinnn07** [stephin007/Cowin-Vaccine-Availablity-Checker#139]
**Is your feature request related to a problem? Please describe.**
The pagination UI doesn't looks attractive and responsive .. 

**Describe the solution you'd like**
Planing of using the pagination from material-ui 
**Describe alternatives you've considered**
We can use Html and css .. 

**Additional context**
Null

**Comment by wise-introvert** [comment]
@Justinnn07 Please use Material UI's [Pagination](https://material-ui.com/components/pagination/#pagination) component.

**Comment by Justinnn07** [comment]
> @Justinnn07 Please use Material UI's [Pagination](https://material-ui.com/components/pagination/#pagination) component. It's styled out of the box and doesn't require additional efforts.

I worked over this, will be raising a PR by today night!

**Comment by wise-introvert** [comment]
@Justinnn07 awesome!

**Comment by stephin007** [comment]
@Justinnn07 closing this as pagination is removed for now and needs to added from scratch 🙏

Will create a separate new issue for pagination

Thanks❤️
