### ISSUE TITLE
Add graphical representation for the data in the world covid info page.

### ISSUE THREAD

**Issue by stephin007** [stephin007/Cowin-Vaccine-Availablity-Checker#154]
**Is your feature request related to a problem? Please describe.**
At the moment, In the world page which has information about covid 19 from around th world. it just shows the numbers. it would be better if we can add graphs,pie charts etc

**Describe the solution you'd like**
The user should not just see number but should be able to visualise the data using graphical methods or pie charts.

**Additional context**
Contributor should first explain what package or anything they will be using. It would better if we can use react-chartjs

Please comment here if you have any further queries

THANKYOU ❤️

**Comment by kunalkumar007** [comment]
I would love to work on this issue.
Requirements:- 
- react-chartjs-2
- chart.js

**Comment by stephin007** [comment]
Yes Understood about the packages that will be involved @kunalkumar007 
Assigning you the issue!

**Comment by stephin007** [comment]
@kunalkumar007 any updates? you haven't been responding!

**Comment by kunalkumar007** [comment]
Ya, I will be completing this today.

**Comment by stephin007** [comment]
Feature added in #163
