### ISSUE TITLE
Add No data found component

### ISSUE THREAD

**Issue by stephin007** [stephin007/Cowin-Vaccine-Availablity-Checker#19]
Initially a loader should be shown and when data is found, A text should be shown saying that, 

**NO DATA FOUND SEARCHED DISTRICT, KINDLY CHECK AFTER SOME TIME**

**Comment by himanshujasuja1040** [comment]
@stephin007 In which page should loader should be placed ?

**Comment by himanshujasuja1040** [comment]
@stephin007 Can you Please Assign me this issue .

**Comment by stephin007** [comment]
@himanshujasuja1040 this issue is same as that of https://github.com/stephin007/Cowin-Vaccine-Availablity-Checker/issues/82

You can check the above issue it has more details, ill be closing this issue soon
