### ISSUE TITLE
Show the cordinates coming in the response in a map component,

### ISSUE THREAD

**Issue by stephin007** [stephin007/Cowin-Vaccine-Availablity-Checker#20]

**Comment by wise-introvert** [comment]
If this hasn't been taken up already, I'd love to take a shot at it.

**Comment by stephin007** [comment]
Please do, @wise-introvert , please create a branch from **NEW-UI**. But please read the documenation because this feature in the API itself is in draft mode, 

PLease let me know how are you planning to implement this: i.e.
- What components will you be editing?
- What new things will you be adding in this?
- How will the UI change ?

Thanks for your interest, looking forward to work with you 🤝

**Comment by wise-introvert** [comment]
@stephin007 I've created a new issue for the marker component. Should we close this one?

**Comment by stephin007** [comment]
Sure @wise-introvert
