### ISSUE TITLE
Add light~dark mode Toggle

### ISSUE THREAD

**Issue by stephin007** [stephin007/Cowin-Vaccine-Availablity-Checker#22]
**Is your feature request related to a problem? Please describe.**
This feature will help to view the app in both day and night

**Comment by teradaian** [comment]
Were you planning on using Styled Components to handle light/dark mode?

**Comment by stephin007** [comment]
@teradaian Right now we are in the initial phase of this project and the team  is yet to figure out a smooth method to implement this, so we can go for the either way, but i prefer using Styled Components. Rest is up to you how you want to implement this.
Any innovation is welcome here 💯 

Shall i assign you this issue? Let me know your thoughts. 

P.S.  Also we are looking for a better UI, if you have anything in mind feel free to start a discussion!

**Comment by stephin007** [comment]
Great asigning this issue to you, please create a branch from the default staging branch, Thanks

**Comment by Justinnn07** [comment]
Hey @teradaian, You can start working with DarkMode,  Please pull the changes from NEW-UI and start working!

Thanks

**Comment by stephin007** [comment]
This feature is added in this PR: #https://github.com/stephin007/Cowin-Vaccine-Availablity-Checker/pull/112
