### ISSUE TITLE
Adding proper documentation

### ISSUE THREAD

**Issue by Ciggzy1312** [stephin007/Cowin-Vaccine-Availablity-Checker#53]
Adding proper documentation about setting up the project in your local environment may act as a guide for other especially beginners to come forward and contribute

**Comment by stephin007** [comment]
Sure, @Ciggzy1312  please make a draft and raise a PR! thanks

**Comment by wise-introvert** [comment]
@Ciggzy1312 happy to help you with this if you want...

**Comment by stephin007** [comment]
@wise-introvert assigned you this to update the documentation for mapbox!
