### ISSUE TITLE
Add Null State Component

### ISSUE THREAD

**Issue by stephin007** [stephin007/Cowin-Vaccine-Availablity-Checker#82]
**Is your feature request related to a problem? Please describe.**
This feature will help in telling the user when no data is being received from the API.

**Describe the solution you'd like**
 This component should show "No results found for the entered State, Pin code or Date, Please Try Again"

**Comment by Yash-271120** [comment]
Hi, Please assign this issue to me! I am new to open source. looking to make contributuions!

**Comment by stephin007** [comment]
Hey @Yash-271120 ofcourse buddy, i am assigning you the issue, 

please make sure you make a branch from the 
"NEW-UI" branch and not the staging branch.

**Comment by himanshujasuja1040** [comment]
@stephin007 Can you please assign this to me .
