### ISSUE TITLE
Add Loading State Component

### ISSUE THREAD

**Issue by stephin007** [stephin007/Cowin-Vaccine-Availablity-Checker#97]
**Is your feature request related to a problem? Please describe.**
There is no feature to show loading when the API is not finished fetching.

**Describe the solution you'd like**
When API is still fetching data, it should show a loading component it can either be a loading gif or a good looking Loading Text

**Comment by rajdama** [comment]
Hi, Please assign this issue to me! I am new to open source. looking to make contribution!

**Comment by stephin007** [comment]
@rajdama Please make sure you make branch from the default **NEW-UI** bbranch.

**Comment by afif1400** [comment]
Can I work on this too?

**Comment by stephin007** [comment]
Sure @afif1400 you can

**Comment by stephin007** [comment]
@rajdama you can also contribute here, no need to withdraw assignment! everyone is welcome to contribute.

**Comment by stephin007** [comment]
@wise-introvert Can you please update your suggestion here as a comment and ill assign you this issue!
Sounds good?

**Comment by stephin007** [comment]
@afif1400 @rajdama Any updates here?
