### ISSUE TITLE
Add Test Cases

### ISSUE THREAD

**Issue by stephin007** [stephin007/Cowin-Vaccine-Availablity-Checker#99]
Please refer this documentation for better explanation:

https://dzone.com/articles/unit-testing-in-reactjs-using-jest-and-enzyme

**Comment by Justinnn07** [comment]
@stephin007 description please!

**Comment by kunalkumar007** [comment]
Is Someone working on the Test Cases? 
I would love to work on this issue.

**Comment by Justinnn07** [comment]
> Is Someone working on the Test Cases?
> I would love to work on this issue.

sure! assigning you the issue! 💥

**Comment by stephin007** [comment]
@kunalkumar007 What is your strategy to add test cases!
Please update the documentation as well

**Comment by stephin007** [comment]
Also Mention:
- If anything is needed to be changed needs in the codebase.
- What all packages will you be using?

It would be great if you could explain everything you are going to do!

**Comment by kunalkumar007** [comment]
> Also @kunalkumar007 Mention:
> 
> * If anything is needed to be changed needs in the codebase.
> * What all packages will you be using?
> 
> It would be great if you could explain everything you are going to do!

Packages I am installing:- **Enzyme**, **Jest**
Changes needed:-We have to roll back react to React v16 in order to Enzyme for working.

**Comment by stephin007** [comment]
Oh, will this roll back create issues with the rest of packages or other functionalities? @kunalkumar007 

I am sure there are other ways also?

**Comment by kunalkumar007** [comment]
> Oh, will this roll back create issues with the rest of packages or other functionalities? @kunalkumar007
> 
> I am sure there are other ways also?

I have tested it and it doesnt break anything in this project.

![testcase1](https://user-images.githubusercontent.com/55233386/120664660-bf6be080-c4a8-11eb-9e74-95e28de01a3b.png)
![testcase2](https://user-images.githubusercontent.com/55233386/120664668-c135a400-c4a8-11eb-9d8b-d182fcdecf78.png)
![Screenshot from 2021-06-03 20-17-19](https://user-images.githubusercontent.com/55233386/120664695-c72b8500-c4a8-11eb-92a0-1cca898cc863.png)

**Comment by stephin007** [comment]
Got it, thanks for the confirmation!
But cant we just use Jest for test cases and also why this downgrade? does jest and enzyme only work with v16 of React?

**Comment by stephin007** [comment]
@kunalkumar007 ^^

**Comment by kunalkumar007** [comment]
Both Jest and Enzyme are specifically designed to test React applications, Jest can be used with any other Javascript app but Enzyme only works with React.
Jest can be used without Enzyme to render components and test with snapshots, Enzyme simply adds additional functionality.

when using **enzyme adapter 16**, the supported version of react are below:-
![enzyme](https://user-images.githubusercontent.com/55233386/120758880-005b0800-c530-11eb-8745-adcbf28093f5.png)

**Comment by stephin007** [comment]
That sounds great @kunalkumar007 ,one final question you will be only adding new files ?or editing all the files while implementing test cases?

I am asking this because a lot of parallel development is going on, will your changes cause conflicts(i know conflicts cannot be eliminated) but i would like to reduce it as much as possible. So, it would be great if  you answer the above question so that you can finally start working on this!

Hoping to work with you on more issues.
Thanks ❤️

**Comment by stephin007** [comment]
hey @kunalkumar007 any updates?

**Comment by kunalkumar007** [comment]
When we write tests, sometimes we have to make changes in the feature files but I believe that those changes are minor onces that will not affect the overall code.
So, if needed I have to make changes in the feature files.

**Comment by stephin007** [comment]
Understood, please proceed! Thanks
